version: '3.8'

services:
  newsletter-db:
    image: postgres:15-alpine
    container_name: newsletter-postgres
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: newsletter123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsletter -d newsletter"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
