// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/unsubscribe": {
    params: {};
  };
  "/post/new": {
    params: {};
  };
  "/post/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/subscribe" | "/unsubscribe" | "/post/new" | "/post/:slug";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/subscribe.tsx": {
    id: "routes/subscribe";
    page: "/subscribe";
  };
  "routes/unsubscribe.tsx": {
    id: "routes/unsubscribe";
    page: "/unsubscribe";
  };
  "routes/new-post.tsx": {
    id: "routes/new-post";
    page: "/post/new";
  };
  "routes/post.$slug.tsx": {
    id: "routes/post.$slug";
    page: "/post/:slug";
  };
};