// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/subscribe": {
    params: {};
  };
  "/post/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/subscribe" | "/post/new";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/subscribe.tsx": {
    id: "routes/subscribe";
    page: "/subscribe";
  };
  "routes/new-post.tsx": {
    id: "routes/new-post";
    page: "/post/new";
  };
};